In [1]:
import csv
import pandas as pd
import json
import datetime
import os

In [2]:
viewing_activity = pd.read_csv('../data/ViewingActivity.csv', sep=',')
viewing_activity

,Profile Name,Start Time,Duration,Attributes,Title,Supplemental Video Type,Device Type,Bookmark,Latest Bookmark,Country
0,Both,2021-11-19 19:51:56,00:00:16,Autoplayed: user action: None;,Informative Clip: Lords of Scam,HOOK,Netflix Linux Firefox Other,00:00:16,00:00:16,FR (France)
1,Both,2021-11-13 12:29:58,00:42:06,NaN,Blacklist: Saison 6: Guillermo Rizal (Épisode 20),NaN,Netflix Linux Firefox Other,00:41:16,00:41:16,FR (France)
2,Both,2021-11-13 12:21:01,00:01:27,NaN,Blacklist: Saison 6: Rassvet (Épisode 19),NaN,Netflix Linux Firefox Other,00:42:26,00:42:26,FR (France)
3,Both,2021-11-13 12:20:45,00:00:08,Autoplayed: user action: None;,Red Notice (Extrait) : Red Notice,HOOK,Netflix Linux Firefox Other,00:00:08,00:00:08,FR (France)
4,Both,2021-11-11 12:15:53,00:42:01,NaN,Blacklist: Saison 6: Rassvet (Épisode 19),NaN,Netflix Linux Firefox Other,00:41:21,Not latest view,FR (France)
...,...,...,...,...,...,...,...,...,...,...
3382,Tarik,2020-04-10 16:54:49,00:00:03,NaN,House of Cards: Saison 1: Chapitre 5 (Épisode 5),NaN,Netflix Linux Firefox Other,00:00:03,00:00:03,FR (France)
3383,Tarik,2020-04-10 16:54:38,00:00:08,NaN,House of Cards: Saison 1: Chapitre 4 (Épisode 4),NaN,Netflix Linux Firefox Other,00:00:08,00:00:08,FR (France)
3384,Tarik,2020-04-10 16:54:33,00:00:01,NaN,House of Cards: Saison 1: Chapitre 3 (Épisode 3),NaN,Netflix Linux Firefox Other,00:00:01,00:00:01,FR (France)
3385,Tarik,2020-04-10 16:54:22,00:00:04,NaN,House of Cards: Saison 1: Chapitre 1 (Épisode 1),NaN,Netflix Linux Firefox Other,00:00:04,00:00:04,FR (France)
3386,Tarik,2020-04-10 16:54:08,00:00:05,NaN,Narcos: Mexico: Saison 1: Le Camelot (Épisode 1),NaN,Netflix Linux Firefox Other,00:00:05,00:00:05,FR (France)

---------------------------------

### Visu 1

In [3]:
viewing_activity = pd.read_csv('../data/ViewingActivity.csv', sep=',')

def sum_duration(duration):
    return float(duration[0:2])*60 + float(duration[3:5]) + float(duration[6:8])/60

def split_title_details(text):
    for i in range(len(text)):
        if (text[i] == ':'):
            return text[0:i], text[i+1:]
    return text, ""

#nettoyage en 4 étapes
start_date = []
start_hour = []
duration = []
title = []
details = []
for i in range(viewing_activity.shape[0]):
    temp = viewing_activity["Start Time"][i].split(' ')
    start_date.append(temp[0])
    start_hour.append(temp[1])
    
    duration.append(sum_duration(viewing_activity["Duration"][i]))
    
    temp_title, temp_details = split_title_details(viewing_activity["Title"][i])
    title.append(temp_title)
    details.append(temp_details)
    

#1. séparation de la date et de l'heure
viewing_activity.drop(columns=['Start Time'], inplace=True)
viewing_activity.insert(1, "Date", start_date, True)
viewing_activity.insert(2, "Time", start_hour, True)

#2. convertion de la durée en minutes
viewing_activity.drop(columns=['Duration'], inplace=True)
viewing_activity.insert(3, "Duration", duration, True)

#3. séparation du titre et des détails
viewing_activity.drop(columns=['Title'], inplace=True)
viewing_activity.insert(4, "Title", title, True)
viewing_activity.insert(5, "Details", details, True)

#4. suppression des données inutiles
viewing_activity.drop(columns=['Attributes'], inplace=True)
viewing_activity.drop(columns=['Supplemental Video Type'], inplace=True)
viewing_activity.drop(columns=['Bookmark'], inplace=True)
viewing_activity.drop(columns=['Latest Bookmark'], inplace=True)
viewing_activity.drop(columns=['Country'], inplace=True)


#Changement nom support
viewing_activity.replace({"Device Type": 'Netflix Linux Firefox Other'}, "Ordinateur", inplace=True)
viewing_activity.replace({'Device Type': "Netflix Windows App - Cadmium Windows Mobile"}, "Ordinateur", inplace=True)
viewing_activity.replace({'Device Type': "Apple iPhone 6s"}, "Smartphone", inplace=True)
viewing_activity.replace({'Device Type': 'Android DefaultWidevineL3Phone Android Phone'}, "Smartphone", inplace=True)
viewing_activity


viewing_activity

,Profile Name,Date,Time,Duration,Title,Details,Device Type
0,Both,2021-11-19,19:51:56,0.266667,Informative Clip,Lords of Scam,Ordinateur
1,Both,2021-11-13,12:29:58,42.100000,Blacklist,Saison 6: Guillermo Rizal (Épisode 20),Ordinateur
2,Both,2021-11-13,12:21:01,1.450000,Blacklist,Saison 6: Rassvet (Épisode 19),Ordinateur
3,Both,2021-11-13,12:20:45,0.133333,Red Notice (Extrait),Red Notice,Ordinateur
4,Both,2021-11-11,12:15:53,42.016667,Blacklist,Saison 6: Rassvet (Épisode 19),Ordinateur
...,...,...,...,...,...,...,...
3382,Tarik,2020-04-10,16:54:49,0.050000,House of Cards,Saison 1: Chapitre 5 (Épisode 5),Ordinateur
3383,Tarik,2020-04-10,16:54:38,0.133333,House of Cards,Saison 1: Chapitre 4 (Épisode 4),Ordinateur
3384,Tarik,2020-04-10,16:54:33,0.016667,House of Cards,Saison 1: Chapitre 3 (Épisode 3),Ordinateur
3385,Tarik,2020-04-10,16:54:22,0.066667,House of Cards,Saison 1: Chapitre 1 (Épisode 1),Ordinateur
3386,Tarik,2020-04-10,16:54:08,0.083333,Narcos,Mexico: Saison 1: Le Camelot (Épisode 1),Ordinateur

----------------------------------------------

In [4]:
def str_to_date(str_date):
    split_date = str_date.split('-')
    year = int(split_date[0])
    month = int(split_date[1])
    day = int(split_date[2])
    return datetime.datetime(year, month, day)
    
def date_to_str(date):
    res = ""
    if date.day < 10:
        res += "0"
    res += str(date.day) + "/"
    if date.month < 10:
        res += "0"
    res += str(date.month) + "/" + str(date.year)
    return res

def get_week_monday(str_date):
    temp = str_to_date(str_date)
    while((int(temp.strftime("%w"))-1)%7 != 0):
        temp = temp - datetime.timedelta(days=1)
    return temp

def get_day_number(str_date):
    split_date = str_date.split('-')
    year = int(split_date[0])
    month = int(split_date[1])
    day = int(split_date[2])
    x = datetime.datetime(year, month, day)
    return (int(x.strftime("%w"))-1)%7

In [5]:
first = get_week_monday(min(viewing_activity['Date']))
last = get_week_monday(max(viewing_activity['Date']))

week_days = []
temp = first
while(last >= temp):
    week_days.append(date_to_str(temp))
    temp = temp + datetime.timedelta(days=7)

with open('../data/week_days.js', 'w') as f:
    f.write("week_days = " + str(week_days).replace('\'', '\"'))

In [6]:
def get_week_number(str_date):
    week_monday = date_to_str(get_week_monday(str_date))
    for i in range(len(week_days)):
        if (week_days[i] == week_monday):
            return i

In [7]:
data = {'ProfileName' : [], 'Date': [], 'Day': [] , 'Week': [], 'Title': [],'Duration': []}
i = 0
while i < viewing_activity.shape[0]:
    if viewing_activity['Duration'][i] > 3:
        j = i
        str_date = viewing_activity['Date'][j]
        day = get_day_number(str_date)
        week = get_week_number(str_date)
        dict_temp = {'Profile Name' : viewing_activity['Profile Name'][j],
                    'Date' : str_date,
                    'Day': day,
                    'Week': week,
                    'Title' : [viewing_activity['Title'][j]],
                    'Duration' : 0}
        same_day = True
        while(same_day and j < viewing_activity.shape[0]):
            if (viewing_activity['Profile Name'][j] == dict_temp["Profile Name"]
                and viewing_activity['Date'][j] == dict_temp["Date"]):
                if viewing_activity['Duration'][j] > 3:
                    if viewing_activity['Title'][j] not in dict_temp["Title"]:
                            dict_temp["Title"].append(viewing_activity['Title'][j])
                    dict_temp["Duration"] += viewing_activity['Duration'][j]
                j = j + 1
            elif (viewing_activity['Date'][j] != dict_temp["Date"]):
                same_day = False
            else:
                j = j + 1
        data["ProfileName"].append(dict_temp["Profile Name"])
        data["Date"].append(dict_temp["Date"])
        data["Day"].append(dict_temp["Day"])
        data["Week"].append(dict_temp["Week"])
        data["Title"].append(dict_temp["Title"])
        data["Duration"].append(dict_temp["Duration"])
        i = j
    else:
        i = i + 1
    
df_viewing_activity = pd.DataFrame.from_dict(data)
df_viewing_activity

,ProfileName,Date,Day,Week,Title,Duration
0,Both,2021-11-13,5,83,[Blacklist],42.100000
1,Both,2021-11-11,3,83,[Blacklist],42.016667
2,Both,2021-11-01,0,82,[Blacklist],49.150000
3,Both,2021-10-26,1,81,[Blacklist],9.300000
4,Both,2021-10-25,0,81,[Blacklist],25.850000
...,...,...,...,...,...,...
750,Tarik,2020-04-14,1,1,[House of Cards],237.016667
751,Tarik,2020-04-13,0,1,[House of Cards],216.000000
752,Tarik,2020-04-12,6,0,[House of Cards],127.450000
753,Tarik,2020-04-11,5,0,"[House of Cards, La casa de papel, 13 Novembre ]",602.500000
754,Tarik,2020-04-10,4,0,[House of Cards],174.733333

In [8]:
#suppression du bruit (bandes annonce, double connexion, extraits, etc.) 
noise_index = []
for i in range(df_viewing_activity.shape[0]):
    if (df_viewing_activity["Duration"][i] < 3):
        noise_index.append(i)
        
df_viewing_activity.drop(noise_index, inplace=True)        

df_viewing_activity

,ProfileName,Date,Day,Week,Title,Duration
0,Both,2021-11-13,5,83,[Blacklist],42.100000
1,Both,2021-11-11,3,83,[Blacklist],42.016667
2,Both,2021-11-01,0,82,[Blacklist],49.150000
3,Both,2021-10-26,1,81,[Blacklist],9.300000
4,Both,2021-10-25,0,81,[Blacklist],25.850000
...,...,...,...,...,...,...
750,Tarik,2020-04-14,1,1,[House of Cards],237.016667
751,Tarik,2020-04-13,0,1,[House of Cards],216.000000
752,Tarik,2020-04-12,6,0,[House of Cards],127.450000
753,Tarik,2020-04-11,5,0,"[House of Cards, La casa de papel, 13 Novembre ]",602.500000
754,Tarik,2020-04-10,4,0,[House of Cards],174.733333

In [9]:
first = get_week_monday(min(viewing_activity['Date']))
last = get_week_monday(max(viewing_activity['Date'])) + datetime.timedelta(days=6)

days_list = []
temp = first
while(last >= temp):
    temp_str = str(temp.year) + "-"
    if temp.month < 10:
        temp_str += "0"
    temp_str += str(temp.month) + "-"
    if temp.day < 10:
        temp_str += "0"
    temp_str += str(temp.day)
    days_list.append(temp_str)
    temp = temp + datetime.timedelta(days=1)
    
days_list

['2020-04-06',
 '2020-04-07',
 '2020-04-08',
 '2020-04-09',
 '2020-04-10',
 '2020-04-11',
 '2020-04-12',
 '2020-04-13',
 '2020-04-14',
 '2020-04-15',
 '2020-04-16',
 '2020-04-17',
 '2020-04-18',
 '2020-04-19',
 '2020-04-20',
 '2020-04-21',
 '2020-04-22',
 '2020-04-23',
 '2020-04-24',
 '2020-04-25',
 '2020-04-26',
 '2020-04-27',
 '2020-04-28',
 '2020-04-29',
 '2020-04-30',
 '2020-05-01',
 '2020-05-02',
 '2020-05-03',
 '2020-05-04',
 '2020-05-05',
 '2020-05-06',
 '2020-05-07',
 '2020-05-08',
 '2020-05-09',
 '2020-05-10',
 '2020-05-11',
 '2020-05-12',
 '2020-05-13',
 '2020-05-14',
 '2020-05-15',
 '2020-05-16',
 '2020-05-17',
 '2020-05-18',
 '2020-05-19',
 '2020-05-20',
 '2020-05-21',
 '2020-05-22',
 '2020-05-23',
 '2020-05-24',
 '2020-05-25',
 '2020-05-26',
 '2020-05-27',
 '2020-05-28',
 '2020-05-29',
 '2020-05-30',
 '2020-05-31',
 '2020-06-01',
 '2020-06-02',
 '2020-06-03',
 '2020-06-04',
 '2020-06-05',
 '2020-06-06',
 '2020-06-07',
 '2020-06-08',
 '2020-06-09',
 '2020-06-10',
 '2020-06-11',
 '2020-06-12',
 '2020-06-13',
 '2020-06-14',
 '2020-06-15',
 '2020-06-16',
 '2020-06-17',
 '2020-06-18',
 '2020-06-19',
 '2020-06-20',
 '2020-06-21',
 '2020-06-22',
 '2020-06-23',
 '2020-06-24',
 '2020-06-25',
 '2020-06-26',
 '2020-06-27',
 '2020-06-28',
 '2020-06-29',
 '2020-06-30',
 '2020-07-01',
 '2020-07-02',
 '2020-07-03',
 '2020-07-04',
 '2020-07-05',
 '2020-07-06',
 '2020-07-07',
 '2020-07-08',
 '2020-07-09',
 '2020-07-10',
 '2020-07-11',
 '2020-07-12',
 '2020-07-13',
 '2020-07-14',
 '2020-07-15',
 '2020-07-16',
 '2020-07-17',
 '2020-07-18',
 '2020-07-19',
 '2020-07-20',
 '2020-07-21',
 '2020-07-22',
 '2020-07-23',
 '2020-07-24',
 '2020-07-25',
 '2020-07-26',
 '2020-07-27',
 '2020-07-28',
 '2020-07-29',
 '2020-07-30',
 '2020-07-31',
 '2020-08-01',
 '2020-08-02',
 '2020-08-03',
 '2020-08-04',
 '2020-08-05',
 '2020-08-06',
 '2020-08-07',
 '2020-08-08',
 '2020-08-09',
 '2020-08-10',
 '2020-08-11',
 '2020-08-12',
 '2020-08-13',
 '2020-08-14',
 '2020-08-15',
 '2020-08-16',
 '2020-08-17',
 '2020-08-18',
 '2020-08-19',
 '2020-08-20',
 '2020-08-21',
 '2020-08-22',
 '2020-08-23',
 '2020-08-24',
 '2020-08-25',
 '2020-08-26',
 '2020-08-27',
 '2020-08-28',
 '2020-08-29',
 '2020-08-30',
 '2020-08-31',
 '2020-09-01',
 '2020-09-02',
 '2020-09-03',
 '2020-09-04',
 '2020-09-05',
 '2020-09-06',
 '2020-09-07',
 '2020-09-08',
 '2020-09-09',
 '2020-09-10',
 '2020-09-11',
 '2020-09-12',
 '2020-09-13',
 '2020-09-14',
 '2020-09-15',
 '2020-09-16',
 '2020-09-17',
 '2020-09-18',
 '2020-09-19',
 '2020-09-20',
 '2020-09-21',
 '2020-09-22',
 '2020-09-23',
 '2020-09-24',
 '2020-09-25',
 '2020-09-26',
 '2020-09-27',
 '2020-09-28',
 '2020-09-29',
 '2020-09-30',
 '2020-10-01',
 '2020-10-02',
 '2020-10-03',
 '2020-10-04',
 '2020-10-05',
 '2020-10-06',
 '2020-10-07',
 '2020-10-08',
 '2020-10-09',
 '2020-10-10',
 '2020-10-11',
 '2020-10-12',
 '2020-10-13',
 '2020-10-14',
 '2020-10-15',
 '2020-10-16',
 '2020-10-17',
 '2020-10-18',
 '2020-10-19',
 '2020-10-20',
 '2020-10-21',
 '2020-10-22',
 '2020-10-23',
 '2020-10-24',
 '2020-10-25',
 '2020-10-26',
 '2020-10-27',
 '2020-10-28',
 '2020-10-29',
 '2020-10-30',
 '2020-10-31',
 '2020-11-01',
 '2020-11-02',
 '2020-11-03',
 '2020-11-04',
 '2020-11-05',
 '2020-11-06',
 '2020-11-07',
 '2020-11-08',
 '2020-11-09',
 '2020-11-10',
 '2020-11-11',
 '2020-11-12',
 '2020-11-13',
 '2020-11-14',
 '2020-11-15',
 '2020-11-16',
 '2020-11-17',
 '2020-11-18',
 '2020-11-19',
 '2020-11-20',
 '2020-11-21',
 '2020-11-22',
 '2020-11-23',
 '2020-11-24',
 '2020-11-25',
 '2020-11-26',
 '2020-11-27',
 '2020-11-28',
 '2020-11-29',
 '2020-11-30',
 '2020-12-01',
 '2020-12-02',
 '2020-12-03',
 '2020-12-04',
 '2020-12-05',
 '2020-12-06',
 '2020-12-07',
 '2020-12-08',
 '2020-12-09',
 '2020-12-10',
 '2020-12-11',
 '2020-12-12',
 '2020-12-13',
 '2020-12-14',
 '2020-12-15',
 '2020-12-16',
 '2020-12-17',
 '2020-12-18',
 '2020-12-19',
 '2020-12-20',
 '2020-12-21',
 '2020-12-22',
 '2020-12-23',
 '2020-12-24',
 '2020-12-25',
 '2020-12-26',
 '2020-12-27',
 '2020-12-28',
 '2020-12-29',
 '2020-12-30',
 '2020-12-31',
 '2021-01-01',
 '2021-01-02',
 '2021-01-03',
 '2021-01-04',
 '2021-01-05',
 '2021-01-06',
 '2021-01-07',
 '2021-01-08',
 '2021-01-09',
 '2021-01-10',
 '2021-01-11',
 '2021-01-12',
 '2021-01-13',
 '2021-01-14',
 '2021-01-15',
 '2021-01-16',
 '2021-01-17',
 '2021-01-18',
 '2021-01-19',
 '2021-01-20',
 '2021-01-21',
 '2021-01-22',
 '2021-01-23',
 '2021-01-24',
 '2021-01-25',
 '2021-01-26',
 '2021-01-27',
 '2021-01-28',
 '2021-01-29',
 '2021-01-30',
 '2021-01-31',
 '2021-02-01',
 '2021-02-02',
 '2021-02-03',
 '2021-02-04',
 '2021-02-05',
 '2021-02-06',
 '2021-02-07',
 '2021-02-08',
 '2021-02-09',
 '2021-02-10',
 '2021-02-11',
 '2021-02-12',
 '2021-02-13',
 '2021-02-14',
 '2021-02-15',
 '2021-02-16',
 '2021-02-17',
 '2021-02-18',
 '2021-02-19',
 '2021-02-20',
 '2021-02-21',
 '2021-02-22',
 '2021-02-23',
 '2021-02-24',
 '2021-02-25',
 '2021-02-26',
 '2021-02-27',
 '2021-02-28',
 '2021-03-01',
 '2021-03-02',
 '2021-03-03',
 '2021-03-04',
 '2021-03-05',
 '2021-03-06',
 '2021-03-07',
 '2021-03-08',
 '2021-03-09',
 '2021-03-10',
 '2021-03-11',
 '2021-03-12',
 '2021-03-13',
 '2021-03-14',
 '2021-03-15',
 '2021-03-16',
 '2021-03-17',
 '2021-03-18',
 '2021-03-19',
 '2021-03-20',
 '2021-03-21',
 '2021-03-22',
 '2021-03-23',
 '2021-03-24',
 '2021-03-25',
 '2021-03-26',
 '2021-03-27',
 '2021-03-28',
 '2021-03-29',
 '2021-03-30',
 '2021-03-31',
 '2021-04-01',
 '2021-04-02',
 '2021-04-03',
 '2021-04-04',
 '2021-04-05',
 '2021-04-06',
 '2021-04-07',
 '2021-04-08',
 '2021-04-09',
 '2021-04-10',
 '2021-04-11',
 '2021-04-12',
 '2021-04-13',
 '2021-04-14',
 '2021-04-15',
 '2021-04-16',
 '2021-04-17',
 '2021-04-18',
 '2021-04-19',
 '2021-04-20',
 '2021-04-21',
 '2021-04-22',
 '2021-04-23',
 '2021-04-24',
 '2021-04-25',
 '2021-04-26',
 '2021-04-27',
 '2021-04-28',
 '2021-04-29',
 '2021-04-30',
 '2021-05-01',
 '2021-05-02',
 '2021-05-03',
 '2021-05-04',
 '2021-05-05',
 '2021-05-06',
 '2021-05-07',
 '2021-05-08',
 '2021-05-09',
 '2021-05-10',
 '2021-05-11',
 '2021-05-12',
 '2021-05-13',
 '2021-05-14',
 '2021-05-15',
 '2021-05-16',
 '2021-05-17',
 '2021-05-18',
 '2021-05-19',
 '2021-05-20',
 '2021-05-21',
 '2021-05-22',
 '2021-05-23',
 '2021-05-24',
 '2021-05-25',
 '2021-05-26',
 '2021-05-27',
 '2021-05-28',
 '2021-05-29',
 '2021-05-30',
 '2021-05-31',
 '2021-06-01',
 '2021-06-02',
 '2021-06-03',
 '2021-06-04',
 '2021-06-05',
 '2021-06-06',
 '2021-06-07',
 '2021-06-08',
 '2021-06-09',
 '2021-06-10',
 '2021-06-11',
 '2021-06-12',
 '2021-06-13',
 '2021-06-14',
 '2021-06-15',
 '2021-06-16',
 '2021-06-17',
 '2021-06-18',
 '2021-06-19',
 '2021-06-20',
 '2021-06-21',
 '2021-06-22',
 '2021-06-23',
 '2021-06-24',
 '2021-06-25',
 '2021-06-26',
 '2021-06-27',
 '2021-06-28',
 '2021-06-29',
 '2021-06-30',
 '2021-07-01',
 '2021-07-02',
 '2021-07-03',
 '2021-07-04',
 '2021-07-05',
 '2021-07-06',
 '2021-07-07',
 '2021-07-08',
 '2021-07-09',
 '2021-07-10',
 '2021-07-11',
 '2021-07-12',
 '2021-07-13',
 '2021-07-14',
 '2021-07-15',
 '2021-07-16',
 '2021-07-17',
 '2021-07-18',
 '2021-07-19',
 '2021-07-20',
 '2021-07-21',
 '2021-07-22',
 '2021-07-23',
 '2021-07-24',
 '2021-07-25',
 '2021-07-26',
 '2021-07-27',
 '2021-07-28',
 '2021-07-29',
 '2021-07-30',
 '2021-07-31',
 '2021-08-01',
 '2021-08-02',
 '2021-08-03',
 '2021-08-04',
 '2021-08-05',
 '2021-08-06',
 '2021-08-07',
 '2021-08-08',
 '2021-08-09',
 '2021-08-10',
 '2021-08-11',
 '2021-08-12',
 '2021-08-13',
 '2021-08-14',
 '2021-08-15',
 '2021-08-16',
 '2021-08-17',
 '2021-08-18',
 '2021-08-19',
 '2021-08-20',
 '2021-08-21',
 '2021-08-22',
 '2021-08-23',
 '2021-08-24',
 '2021-08-25',
 '2021-08-26',
 '2021-08-27',
 '2021-08-28',
 '2021-08-29',
 '2021-08-30',
 '2021-08-31',
 '2021-09-01',
 '2021-09-02',
 '2021-09-03',
 '2021-09-04',
 '2021-09-05',
 '2021-09-06',
 '2021-09-07',
 '2021-09-08',
 '2021-09-09',
 '2021-09-10',
 '2021-09-11',
 '2021-09-12',
 '2021-09-13',
 '2021-09-14',
 '2021-09-15',
 '2021-09-16',
 '2021-09-17',
 '2021-09-18',
 '2021-09-19',
 '2021-09-20',
 '2021-09-21',
 '2021-09-22',
 '2021-09-23',
 '2021-09-24',
 '2021-09-25',
 '2021-09-26',
 '2021-09-27',
 '2021-09-28',
 '2021-09-29',
 '2021-09-30',
 '2021-10-01',
 '2021-10-02',
 '2021-10-03',
 '2021-10-04',
 '2021-10-05',
 '2021-10-06',
 '2021-10-07',
 '2021-10-08',
 '2021-10-09',
 '2021-10-10',
 '2021-10-11',
 '2021-10-12',
 '2021-10-13',
 '2021-10-14',
 '2021-10-15',
 '2021-10-16',
 '2021-10-17',
 '2021-10-18',
 '2021-10-19',
 '2021-10-20',
 '2021-10-21',
 '2021-10-22',
 '2021-10-23',
 '2021-10-24',
 '2021-10-25',
 '2021-10-26',
 '2021-10-27',
 '2021-10-28',
 '2021-10-29',
 '2021-10-30',
 '2021-10-31',
 '2021-11-01',
 '2021-11-02',
 '2021-11-03',
 '2021-11-04',
 '2021-11-05',
 '2021-11-06',
 '2021-11-07',
 '2021-11-08',
 '2021-11-09',
 '2021-11-10',
 '2021-11-11',
 '2021-11-12',
 '2021-11-13',
 '2021-11-14',
 '2021-11-15',
 '2021-11-16',
 '2021-11-17',
 '2021-11-18',
 '2021-11-19',
 '2021-11-20',
 '2021-11-21']

In [10]:
profiles = ["Both", "Hana", "Tarik"]

def build_empty_row(profile_, date_):
    return {"Date": date_, "ProfileName" : profile_,  
            "Day": get_day_number(date_), "Week": get_week_number(date_),
            "Title": [], "Duration" : 0}

#def build_row()

dict_viewing_activity = {}

for d in days_list:
    temp = df_viewing_activity[df_viewing_activity["Date"] == d]
    dict_viewing_activity[d] = {}
    for p in profiles:
        dict_viewing_activity[d][p] = build_empty_row(p, d)
        
for d in days_list:
    temp = df_viewing_activity[df_viewing_activity["Date"] == d]
    dict_viewing_activity[d] = {}
    for p in profiles:
        dict_viewing_activity[d][p] = build_empty_row(p, d)
    
for i in df_viewing_activity.index:
    dict_viewing_activity[df_viewing_activity["Date"][i]][df_viewing_activity["ProfileName"][i]] = {"Date": df_viewing_activity["Date"][i], "ProfileName" : df_viewing_activity["ProfileName"][i],  
            "Day": df_viewing_activity["Day"][i], "Week": df_viewing_activity["Week"][i],
            "Title": df_viewing_activity["Title"][i], "Duration" : df_viewing_activity["Duration"][i]}

tuples = []
for d, v in dict_viewing_activity.items():
    for p, t in v.items():
        tuples.append(t)

In [11]:
df = pd.DataFrame(columns=df_viewing_activity.columns)
for t in tuples:
    df = df.append(t, ignore_index=True)
    
df

     ProfileName        Date Day Week           Title Duration
0           Both  2020-04-06   0    0              []        0
1           Hana  2020-04-06   0    0              []        0
2          Tarik  2020-04-06   0    0              []        0
3           Both  2020-04-07   1    0              []        0
4           Hana  2020-04-07   1    0              []        0
...          ...         ...  ..  ...             ...      ...
1780        Hana  2021-11-20   5   84  [Another Life]  31.3667
1781       Tarik  2021-11-20   5   84    [Formula 1 ]  9.13333
1782        Both  2021-11-21   6   84              []        0
1783        Hana  2021-11-21   6   84              []        0
1784       Tarik  2021-11-21   6   84              []        0

[1785 rows x 6 columns]

In [12]:
for i in df.index:
    df["Date"][i] = date_to_str(str_to_date(df["Date"][i]))

In [13]:
result = df.to_json(orient="records")

parsed = json.loads(result)

json.dumps(parsed)

with open('../data/viewing_activity.json', 'w') as f:
    json.dump(parsed, f )

----------------------------------

### Visu 2

In [14]:
device_type = {"Both" : {}, "Tarik": {}, "Hana": {}, "Kids": {}}

for i in range(viewing_activity.shape[0]):
    if viewing_activity["Device Type"].values[i] in device_type[viewing_activity["Profile Name"][i]]:
        device_type[viewing_activity["Profile Name"][i]][viewing_activity["Device Type"][i]] += viewing_activity["Duration"][i]
    else:
        device_type[viewing_activity["Profile Name"][i]][viewing_activity["Device Type"][i]] = viewing_activity["Duration"][i]
        
del device_type["Kids"]
device_type

{'Both': {'Ordinateur': 7579.300000000002},
 'Tarik': {'Ordinateur': 10452.466666666665, 'Smartphone': 6278.966666666667},
 'Hana': {'Smartphone': 38598.14999999996, 'Ordinateur': 220.31666666666666}}

In [15]:
with open('../data/device_type.json', 'w', encoding='utf-8') as f:
    json.dump(device_type, f, ensure_ascii=False, indent=4)

------------------------------------

### Visu 3

In [25]:
viewing_activity

week_activity = {"Both": {}, "Hana": {}, "Tarik": {}}


for i in range(len(week_days)):
    for k, v in week_activity.items():
        week_activity[k][i] = 0 

for i in viewing_activity.index:
    if viewing_activity["Duration"][i] > 3:
        week_activity[viewing_activity["Profile Name"][i]][get_week_number(viewing_activity["Date"][i])] \
                += viewing_activity["Duration"][i]

{'Both': {0: 0,
  1: 0,
  2: 0,
  3: 0,
  4: 0,
  5: 0,
  6: 0,
  7: 368.29999999999995,
  8: 236.88333333333333,
  9: 175.71666666666667,
  10: 106.93333333333334,
  11: 228.2,
  12: 272.75,
  13: 0,
  14: 65.05,
  15: 0,
  16: 155.48333333333335,
  17: 123.16666666666666,
  18: 0,
  19: 132.76666666666668,
  20: 128.56666666666666,
  21: 125.75,
  22: 43.38333333333333,
  23: 0,
  24: 105.39999999999999,
  25: 190.01666666666665,
  26: 0,
  27: 143.85,
  28: 31.816666666666666,
  29: 54.63333333333333,
  30: 88.48333333333333,
  31: 0,
  32: 0,
  33: 0,
  34: 0,
  35: 52.0,
  36: 35.13333333333333,
  37: 127.76666666666668,
  38: 312.4666666666667,
  39: 169.81666666666666,
  40: 170.70000000000002,
  41: 51.31666666666667,
  42: 246.96666666666667,
  43: 0,
  44: 123.85000000000001,
  45: 194.08333333333331,
  46: 0,
  47: 53.8,
  48: 0,
  49: 241.23333333333335,
  50: 9.983333333333333,
  51: 76.55000000000001,
  52: 139.60000000000002,
  53: 0,
  54: 0,
  55: 0,
  56: 110.85000000000001,
  57: 82.39999999999999,
  58: 133.66666666666666,
  59: 146.01666666666668,
  60: 95.66666666666667,
  61: 229.51666666666665,
  62: 325.2,
  63: 326.3666666666666,
  64: 227.35000000000002,
  65: 125.78333333333333,
  66: 0,
  67: 0,
  68: 437.08333333333337,
  69: 0,
  70: 79.01666666666667,
  71: 0,
  72: 0,
  73: 112.71666666666665,
  74: 21.816666666666666,
  75: 0,
  76: 42.41666666666667,
  77: 0,
  78: 42.68333333333334,
  79: 0,
  80: 42.35,
  81: 35.150000000000006,
  82: 49.150000000000006,
  83: 84.11666666666667,
  84: 0},
 'Hana': {0: 218.73333333333332,
  1: 718.1333333333334,
  2: 518.6333333333333,
  3: 458.41666666666663,
  4: 961.2833333333334,
  5: 783.5333333333333,
  6: 267.8666666666667,
  7: 324.28333333333336,
  8: 600.3666666666667,
  9: 681.0166666666665,
  10: 759.85,
  11: 114.51666666666668,
  12: 745.7166666666667,
  13: 646.9999999999999,
  14: 495.23333333333335,
  15: 426.73333333333335,
  16: 105.06666666666666,
  17: 518.1500000000001,
  18: 1037.7166666666665,
  19: 827.9333333333334,
  20: 826.5166666666667,
  21: 236.33333333333331,
  22: 285.58333333333326,
  23: 272.1000000000001,
  24: 234.43333333333334,
  25: 218.40000000000003,
  26: 282.03333333333336,
  27: 512.1166666666666,
  28: 112.44999999999999,
  29: 355.55,
  30: 441.06666666666666,
  31: 637.6999999999999,
  32: 600.5,
  33: 591.9333333333333,
  34: 607.4000000000001,
  35: 936.183333333333,
  36: 1285.9500000000003,
  37: 706.9166666666666,
  38: 525.3833333333334,
  39: 741.9166666666666,
  40: 505.4833333333333,
  41: 347.8166666666666,
  42: 878.6500000000002,
  43: 137.21666666666667,
  44: 827.5833333333331,
  45: 390.1333333333333,
  46: 374.8,
  47: 752.8999999999997,
  48: 748.2166666666666,
  49: 191.8,
  50: 590.9666666666668,
  51: 611.9666666666668,
  52: 372.45,
  53: 83.55000000000001,
  54: 0,
  55: 0,
  56: 63.483333333333334,
  57: 118.68333333333334,
  58: 253.71666666666667,
  59: 96.51666666666667,
  60: 415.53333333333336,
  61: 85.51666666666667,
  62: 134.14999999999998,
  63: 87.08333333333333,
  64: 458.8666666666667,
  65: 602.6666666666667,
  66: 628.4999999999999,
  67: 168.03333333333333,
  68: 19.0,
  69: 85.55,
  70: 584.8833333333333,
  71: 511.86666666666673,
  72: 297.18333333333334,
  73: 306.50000000000006,
  74: 719.2166666666669,
  75: 577.1833333333334,
  76: 543.4666666666667,
  77: 491.7,
  78: 372.9833333333333,
  79: 477.51666666666677,
  80: 612.1166666666667,
  81: 139.9,
  82: 435.68333333333334,
  83: 432.0166666666667,
  84: 365.3333333333333},
 'Tarik': {0: 904.6833333333333,
  1: 1491.2000000000003,
  2: 168.03333333333333,
  3: 560.2500000000001,
  4: 341.9666666666667,
  5: 1205.6499999999996,
  6: 879.0333333333334,
  7: 270.45,
  8: 309.7,
  9: 0,
  10: 0,
  11: 159.55,
  12: 0,
  13: 0,
  14: 346.0166666666666,
  15: 309.18333333333334,
  16: 33.03333333333333,
  17: 529.95,
  18: 15.35,
  19: 15.183333333333334,
  20: 0,
  21: 0,
  22: 0,
  23: 261.56666666666666,
  24: 74.44999999999999,
  25: 138.79999999999998,
  26: 371.29999999999995,
  27: 505.33333333333337,
  28: 294.9,
  29: 579.9666666666667,
  30: 393.48333333333335,
  31: 443.29999999999995,
  32: 89.53333333333333,
  33: 224.44999999999996,
  34: 11.733333333333333,
  35: 0,
  36: 187.33333333333334,
  37: 193.85,
  38: 0,
  39: 0,
  40: 0,
  41: 312.5,
  42: 295.8666666666666,
  43: 122.68333333333334,
  44: 179.75,
  45: 0,
  46: 54.81666666666666,
  47: 0,
  48: 0,
  49: 128.71666666666664,
  50: 0,
  51: 237.26666666666668,
  52: 26.233333333333334,
  53: 0,
  54: 0,
  55: 0,
  56: 0,
  57: 0,
  58: 61.45,
  59: 304.68333333333334,
  60: 321.4333333333334,
  61: 136.25,
  62: 124.33333333333334,
  63: 134.85,
  64: 0,
  65: 0,
  66: 0,
  67: 46.81666666666667,
  68: 272.8333333333333,
  69: 127.48333333333333,
  70: 482.50000000000006,
  71: 942.6333333333334,
  72: 151.79999999999998,
  73: 254.61666666666665,
  74: 387.7833333333334,
  75: 167.5,
  76: 0,
  77: 0,
  78: 0,
  79: 0,
  80: 0,
  81: 0,
  82: 0,
  83: 0,
  84: 9.133333333333333}}

In [26]:
with open('../data/week_activity.json', 'w', encoding='utf-8') as f:
    json.dump(week_activity, f, ensure_ascii=False, indent=4)